var define = {
	COEFF: 35,
	sunblind: {
		ID_VERTICAL: 1,
		ID_HORIZONTAL: 2,
		ID_MULTI: 3,
		ID_ROLL: 4,
		ID_AMILUX: 5,
		MIN_CORNICE_LENGTH: 0.7,
		MIN_LAYER_SQUARE: 1.0,
		ID_DECOR_VERTICAL: 7,
		ID_DECOR_HORIZONTAL: 8
	}
};